! (C) Copyright 2000- ECMWF.
! (C) Copyright 2000- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE TPM_FFTW
!   Author.
!   -------
!     George Mozdzynski
!
!   Modifications.
!   -------------- 
!     Original      October 2014
!     R. El Khatib 01-Sep-2015 More subroutines for better modularity

USE, INTRINSIC :: ISO_C_BINDING
USE TPM_GEN    ,ONLY : LALLOPERM
USE PARKIND1   ,ONLY : JPIB, JPIM, JPRB, JPRD
USE MPL_MODULE ,ONLY : MPL_MYRANK
USE YOMHOOK    ,ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

SAVE

#include "abor1.intfb.h"

#ifdef __NEC__
! From NLC (NEC Numeric Library Collection)
#include "aslfftw3.f03"
#define FFTW_NO_SIMD 0
#else
#include "fftw3.f03"
#endif

PRIVATE
PUBLIC EC_FFTW_INIT, EC_FFTW_FINALIZE, SET_FFTW_RESOL, EXEC_FFTW

INTERFACE EXEC_FFTW
   MODULE PROCEDURE EXEC_FFTW_SINGLE_COLUMN
   MODULE PROCEDURE EXEC_FFTW_SINGLE_COLUMN_INPLACE
#ifdef CPU_FFTW_INPLACE
   MODULE PROCEDURE EXEC_FFTW_MULTI_COLUMN_INPLACE
#else
   MODULE PROCEDURE EXEC_FFTW_MULTI_COLUMN
#endif
END INTERFACE

INTERFACE TPM_FFTW_GET_PLAN_DIR
   MODULE PROCEDURE GET_PLAN_FFTW_DIR_R1
END INTERFACE TPM_FFTW_GET_PLAN_DIR

INTERFACE TPM_FFTW_GET_PLAN_INV
   MODULE PROCEDURE GET_PLAN_FFTW_INV_R1   
END INTERFACE TPM_FFTW_GET_PLAN_INV

INTERFACE TPM_FFTW_EXECUTE_DFT_INV
   MODULE PROCEDURE TPM_FFTW_EXECUTE_DFT_INV_R1, TPM_FFTW_EXECUTE_DFT_INV_R2
END INTERFACE TPM_FFTW_EXECUTE_DFT_INV

INTERFACE TPM_FFTW_EXECUTE_DFT_DIR
   MODULE PROCEDURE TPM_FFTW_EXECUTE_DFT_DIR_R1, TPM_FFTW_EXECUTE_DFT_DIR_R2
END INTERFACE TPM_FFTW_EXECUTE_DFT_DIR

INTERFACE TPM_FFTW_ALLOCATE_MEMORY
   MODULE PROCEDURE TPM_FFTW_ALLOCATE_MEMORY_R1, TPM_FFTW_ALLOCATE_MEMORY_R2
END INTERFACE TPM_FFTW_ALLOCATE_MEMORY

INTERFACE TPM_FFTW_DFT_INV
   MODULE PROCEDURE TPM_FFTW_DFT_INV_R1, TPM_FFTW_DFT_INV_R1_INPLACE, TPM_FFTW_DFT_INV_R2 
END INTERFACE TPM_FFTW_DFT_INV

INTERFACE TPM_FFTW_DFT_DIR
   MODULE PROCEDURE TPM_FFTW_DFT_DIR_R1, TPM_FFTW_DFT_DIR_R1_INPLACE, TPM_FFTW_DFT_DIR_R2
END INTERFACE TPM_FFTW_DFT_DIR

INTEGER(KIND=JPIB),ALLOCATABLE :: FFTW_DIR_R1(:)
INTEGER(KIND=JPIB),ALLOCATABLE :: FFTW_INV_R1(:)
LOGICAL     :: EC_FFTW_INITIALIZED=.FALSE.
INTEGER(KIND=JPIM) :: CURRENT_RESOL = 0
TYPE(C_PTR) :: ZFFTWP = C_NULL_PTR
INTEGER(C_SIZE_T) :: ZFFTWP_SIZE = 0

!$OMP THREADPRIVATE(ZFFTWP, ZFFTWP_SIZE)

! ------------------------------------------------------------------
CONTAINS
! ------------------------------------------------------------------

SUBROUTINE SET_FFTW_RESOL(KCUR_RESOL)
#if defined (_OPENMP)
  USE OMP_LIB,   only : OMP_IN_PARALLEL
#endif
  IMPLICIT NONE
  INTEGER(KIND=JPIM),INTENT(IN) :: KCUR_RESOL
#if defined (_OPENMP)
  IF (OMP_IN_PARALLEL()) THEN
    CALL ABOR1('SET_FFTW_RESOL: CANNOT BE CALLED IN OMP PARALLEL CONTEXT')
  ENDIF
#endif
  IF (CURRENT_RESOL.ne.KCUR_RESOL) THEN
    IF (CURRENT_RESOL.ne.0) THEN
!      write (*,*) 'DEBUG SURPRISE ', CURRENT_RESOL, KCUR_RESOL
      ! 4608/12/2 = 192
!      CALL ABOR1('SET_FFTW_RESOL: REDO plans not done yet')
!      CALL DESTROY_PLANS_FFTW()
!      CALL EC_FFTW_INIT_PLAN()
    ELSE
      !CALL ABOR1('SET_FFTW_RESOL: init plans from SET_FFTW_RESOL not done yet')
!      CALL EC_FFTW_INIT_PLAN() ! FIXME R is not set at this stage 
    ENDIF
    CURRENT_RESOL = KCUR_RESOL
!    write (*,*) 'DEBUG: CALLED SET_FFTW_RESOL ', KCUR_RESOL
!    ! 5760-4608 = 1152, 1152/12=96
  ENDIF
END SUBROUTINE SET_FFTW_RESOL

SUBROUTINE EC_FFTW_FINALIZE()
  IMPLICIT NONE
  CALL DESTROY_PLANS_FFTW()
END SUBROUTINE EC_FFTW_FINALIZE

SUBROUTINE EC_FFTW_INIT(KDLON,NMAX_RESOL,KCUR_RESOL)
  USE FOURIER_OUT_MOD ,ONLY : FOURIER_OUT_SETUP
  IMPLICIT NONE
  INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
  INTEGER(KIND=JPIM),INTENT(IN) :: NMAX_RESOL
  INTEGER(KIND=JPIM),INTENT(IN) :: KCUR_RESOL
!  CALL EC_FFTW_INIT_RESOL_AD(NMAX_RESOL) ! FIXME initialize ADJOINT internals
  !$OMP PARALLEL
  ZFFTWP = C_NULL_PTR
  ZFFTWP_SIZE = 0
  !$OMP END PARALLEL
  CALL SET_FFTW_RESOL(KCUR_RESOL)
  CALL EC_FFTW_INIT_PLAN(KDLON)
  CALL FOURIER_OUT_SETUP()
  EC_FFTW_INITIALIZED=.TRUE.
END SUBROUTINE EC_FFTW_INIT

SUBROUTINE EC_FFTW_INIT_PLAN(KDLON)
  USE TPM_DIM,      ONLY : R
  USE TPM_GEOMETRY, ONLY : G
  IMPLICIT NONE
  INTEGER(KIND=JPIM),OPTIONAL, INTENT(IN) :: KDLON

  INTEGER(KIND=JPIM) :: I, FAKEKN

  IF (.NOT.G%LREDUCED_GRID) THEN
    IF (PRESENT(KDLON)) THEN
      ALLOCATE(FFTW_DIR_R1(KDLON))
      FFTW_DIR_R1(:)=123456
      ALLOCATE(FFTW_INV_R1(KDLON))
      FFTW_INV_R1(:)=123456
    ENDIF
    STOP 'NOT TESTED YET, ONLY TESTED FOR FOR REDUCED GRIDS'
    ! FIXME create plans for regular GAUSSIAN grid here
  ELSE
    ! NOTE - assumes that R%NSMAX is properly set per resolution, i.e. that
    ! we can rely on R%NSMAX also in DA context where resolution is being changed
    ! during the same incarnation
    ALLOCATE(FFTW_DIR_R1(R%NSMAX+1))
    FFTW_DIR_R1(:)=123456
    ALLOCATE(FFTW_INV_R1(R%NSMAX+1))
    FFTW_INV_R1(:)=123456
    DO I = (R%NSMAX+1), 1, -1 
      ! avoid re-allocations by taking the largest first
      FAKEKN = 20 + 4 * (i - 1)
      CALL CREATE_PLAN_FFTW_DIR_R1(FAKEKN)
      CALL CREATE_PLAN_FFTW_INV_R1(FAKEKN)
    ENDDO
  ENDIF
END SUBROUTINE EC_FFTW_INIT_PLAN

SUBROUTINE CREATE_PLAN_FFTW_INV_R1(KN)
USE TPM_GEOMETRY, ONLY : G
#if defined (_OPENMP)
    USE OMP_LIB,   only : OMP_IN_PARALLEL
#endif
INTEGER(KIND=JPIM),INTENT(IN)        :: KN
INTEGER(KIND=JPIB)                   :: IPLAN
INTEGER(KIND=JPIM)                   :: KNIDX
REAL(KIND=JPHOOK)                    :: ZHOOK_HANDLE, ZHOOK_HANDLE2
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: ZDUM(:)

IF (LHOOK) CALL DR_HOOK('CREATE_PLAN_FFTW_INV_R1',0,ZHOOK_HANDLE)

#if defined (_OPENMP)
IF (OMP_IN_PARALLEL()) THEN
  CALL ABOR1('CREATE_PLAN_FFTW_INV_R1: CANNOT BE CALLED IN OMP PARALLEL CONTEXT')
ENDIF
#endif

IF (.NOT.G%LREDUCED_GRID) THEN
  KNIDX=KN ! maintaining the original strategy for regular Gaussion
ELSE
  KNIDX=(((KN-20)/4) + 1) ! compute index for plans to allow for reduced footprint
ENDIF

IF( KNIDX > SIZE(FFTW_INV_R1) )THEN
  CALL ABOR1('CREATE_PLAN_FFTW_INV_R1: KNIDX > N_MAX THAT WAS INITIALISED IN INIT_PLANS_FFTW')
ENDIF

IF (FFTW_INV_R1(KNIDX) == 123456 )THEN
   CALL TPM_FFTW_ALLOCATE_MEMORY_R1(KN, ZDUM)
   IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_DFT_C2R_1D',0,ZHOOK_HANDLE2)
   IF (JPRB == JPRD) THEN
      CALL DFFTW_PLAN_DFT_C2R_1D(IPLAN,KN,ZDUM,ZDUM,FFTW_ESTIMATE+FFTW_UNALIGNED)
   ELSE
      CALL SFFTW_PLAN_DFT_C2R_1D(IPLAN,KN,ZDUM,ZDUM,FFTW_ESTIMATE+FFTW_UNALIGNED)
      ! Note that MKL allow FFTW_MEASURE, but libfftw3 does not when doing it in-place
      ! Work-around for FFTW_MEASURE with libfftw3 is to add the +FFTW_UNALIGNED coming from KOFF:
   ENDIF
   IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_DFT_C2R_1D',1,ZHOOK_HANDLE2)
   FFTW_INV_R1(KNIDX)=IPLAN
ELSE
  CALL ABOR1('CREATE_PLAN_FFTW_INV_R1 HAS RECEIVED TWO CALLS TO CREATE SAME PLAN')
ENDIF
IF (LHOOK) CALL DR_HOOK('CREATE_PLAN_FFTW_INV_R1',1,ZHOOK_HANDLE)
END SUBROUTINE CREATE_PLAN_FFTW_INV_R1

SUBROUTINE CREATE_PLAN_FFTW_DIR_R1(KN)
USE TPM_GEOMETRY, ONLY : G
#if defined (_OPENMP)
  USE OMP_LIB,   only : OMP_IN_PARALLEL
#endif
INTEGER(KIND=JPIM),INTENT(IN)        :: KN
INTEGER(KIND=JPIB)                   :: IPLAN
INTEGER(KIND=JPIM)                   :: KNIDX
REAL(KIND=JPHOOK)                    :: ZHOOK_HANDLE, ZHOOK_HANDLE2
REAL(KIND=JPRB), POINTER, CONTIGUOUS :: ZDUM(:)

IF (LHOOK) CALL DR_HOOK('CREATE_PLAN_FFTW_DIR_R1',0,ZHOOK_HANDLE)

#if defined (_OPENMP)
IF (OMP_IN_PARALLEL()) THEN
  CALL ABOR1('CREATE_PLAN_FFTW_DIR_R1: CANNOT BE CALLED IN OMP PARALLEL CONTEXT')
ENDIF
#endif

IF (.NOT.G%LREDUCED_GRID) THEN
  KNIDX=KN ! maintaining the original strategy for regular Gaussion
ELSE
  KNIDX=(((KN-20)/4) + 1) ! compute index for plans to allow for reduced footprint
ENDIF

IF( KNIDX > SIZE(FFTW_DIR_R1) )THEN
  CALL ABOR1('CREATE_PLAN_FFTW_DIR_R1: KNIDX > N_MAX THAT WAS INITIALISED IN INIT_PLANS_FFTW')
ENDIF

IF (FFTW_DIR_R1(KNIDX) == 123456 )THEN
   CALL TPM_FFTW_ALLOCATE_MEMORY_R1(KN, ZDUM)
   IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_DFT_R2C_1D',0,ZHOOK_HANDLE2)
   IF (JPRB == JPRD) THEN
      CALL DFFTW_PLAN_DFT_R2C_1D(IPLAN,KN,ZDUM,ZDUM,FFTW_ESTIMATE+FFTW_UNALIGNED)
   ELSE
      CALL SFFTW_PLAN_DFT_R2C_1D(IPLAN,KN,ZDUM,ZDUM,FFTW_ESTIMATE+FFTW_UNALIGNED)
      ! Work-around for FFTW_MEASURE with libfftw3 is to add the +FFTW_UNALIGNED coming from KOFF.
      ! CALL SFFTW_PLAN_DFT_C2R_1D(IPLAN,KN,ZDUM,ZDUM,FFTW_MEASURE+FFTW_UNALIGNED)
   ENDIF
   IF (LHOOK) CALL DR_HOOK('FFTW_PLAN_DFT_R2C_1D',1,ZHOOK_HANDLE2)
   FFTW_DIR_R1(KNIDX)=IPLAN
ELSE
  CALL ABOR1('CREATE_PLAN_FFTW_DIR_R1 HAS RECEIVED TWO CALLS TO CREATE SAME PLAN')
ENDIF
IF (LHOOK) CALL DR_HOOK('CREATE_PLAN_FFTW_DIR_R1',1,ZHOOK_HANDLE)
END SUBROUTINE CREATE_PLAN_FFTW_DIR_R1

SUBROUTINE GET_PLAN_FFTW_INV_R1(KPLAN,KN)
USE TPM_GEOMETRY, ONLY : G
INTEGER(KIND=JPIB),INTENT(OUT) :: KPLAN
INTEGER(KIND=JPIM),INTENT(IN)  :: KN
REAL(KIND=JPHOOK)        :: ZHOOK_HANDLE
INTEGER(KIND=JPIM)       :: KNIDX

IF (LHOOK) CALL DR_HOOK('GET_PLAN_FFTW_INV_R1',0,ZHOOK_HANDLE)

IF (.NOT.G%LREDUCED_GRID) THEN
  KNIDX=KN ! maintaining the original strategy for regular Gaussion
ELSE
  KNIDX=(((KN-20)/4) + 1) ! compute index for plans to allow for reduced footprint
ENDIF

IF( KNIDX > SIZE(FFTW_INV_R1) )THEN
  CALL ABOR1('GET_PLAN_FFTW_INV_R1: KNIDX > N_MAX THAT WAS INITIALISED IN INIT_PLANS_FFTW')
ENDIF

IF (FFTW_INV_R1(KNIDX) == 123456 )THEN
   WRITE (*,*) 'FFTW PLAN NOT CREATED PRIOR TO USE', KN, KNIDX
   CALL ABOR1('GET_PLAN_FFTW_INV_R1: NOT CREATED PRIOR TO USE')
ENDIF
KPLAN=FFTW_INV_R1(KNIDX)
IF (LHOOK) CALL DR_HOOK('GET_PLAN_FFTW_INV_R1',1,ZHOOK_HANDLE)
END SUBROUTINE GET_PLAN_FFTW_INV_R1

SUBROUTINE GET_PLAN_FFTW_DIR_R1(KPLAN,KN)
USE TPM_GEOMETRY, ONLY : G
INTEGER(KIND=JPIB),INTENT(OUT) :: KPLAN
INTEGER(KIND=JPIM),INTENT(IN)  :: KN
REAL(KIND=JPHOOK)        :: ZHOOK_HANDLE
INTEGER(KIND=JPIM)       :: KNIDX

IF (LHOOK) CALL DR_HOOK('GET_PLAN_FFTW_DIR_R1',0,ZHOOK_HANDLE)

IF (.NOT.G%LREDUCED_GRID) THEN
  KNIDX=KN ! maintaining the original strategy for regular Gaussion
ELSE
  KNIDX=(((KN-20)/4) + 1) ! compute index for plans to allow for reduced footprint
ENDIF

IF( KNIDX > SIZE(FFTW_DIR_R1) )THEN
  CALL ABOR1('GET_PLAN_FFTW_DIR_R1: KNIDX > N_MAX THAT WAS INITIALISED IN INIT_PLANS_FFTW')
ENDIF

IF (FFTW_DIR_R1(KNIDX) == 123456 )THEN
   WRITE (*,*) 'FFTW PLAN NOT CREATED PRIOR TO USE', KN, KNIDX
   CALL ABOR1('GET_PLAN_FFTW_DIR_R1: NOT CREATED PRIOR TO USE')
ENDIF
KPLAN=FFTW_DIR_R1(KNIDX)
IF (LHOOK) CALL DR_HOOK('GET_PLAN_FFTW_DIR_R1',1,ZHOOK_HANDLE)
END SUBROUTINE GET_PLAN_FFTW_DIR_R1

SUBROUTINE DESTROY_PLAN_FFTW(KPLAN)
INTEGER(KIND=JPIB),INTENT(IN) :: KPLAN
!$OMP CRITICAL (FFTW_DESTROY)
IF (JPRB == JPRD) THEN
   CALL DFFTW_DESTROY_PLAN(KPLAN)
ELSE
   CALL SFFTW_DESTROY_PLAN(KPLAN)
END IF
!$OMP END CRITICAL (FFTW_DESTROY)
RETURN
END SUBROUTINE DESTROY_PLAN_FFTW

SUBROUTINE DESTROY_PLANS_FFTW()
#ifdef DEBUG_PLAN_ID
USE TPM_DISTR  ,ONLY : MYPROC
#endif

#ifdef DEBUG_PLAN_ID
  WRITE(*,*) 'DEBUG FFTW PLAN DIR array - never used: ', MYPROC, count(FFTW_DIR_R1==123456), size(FFTW_DIR_R1)
  WRITE(*,*) 'DEBUG FFTW PLAN DIR array - used:', MYPROC, count(FFTW_DIR_R1/=123456), size(FFTW_DIR_R1)
  WRITE(*,*) 'DEBUG FFTW PLAN INV array - never used: ', MYPROC, count(FFTW_INV_R1==123456), size(FFTW_INV_R1)
  WRITE(*,*) 'DEBUG FFTW PLAN INV array - used:', MYPROC, count(FFTW_INV_R1/=123456), size(FFTW_INV_R1)
  WRITE(*,*) 'DEBUG DIR indices:', MYPROC, PACK([(i,i=1,SIZE(FFTW_DIR_R1))], FFTW_DIR_R1/=123456 )
  WRITE(*,*) 'DEBUG INV indices:', MYPROC, PACK([(i,i=1,SIZE(FFTW_INV_R1))], FFTW_INV_R1/=123456 )
#endif
! Free FFTW memory
!CALL DEALLOCATE_MEMORY_FFTW( ZFFTWP )
END SUBROUTINE DESTROY_PLANS_FFTW

SUBROUTINE ALLOCATE_MEMORY_FFTW( FFTWMEM_PTR, NMEM )
  TYPE(C_PTR) :: FFTWMEM_PTR
  INTEGER(C_SIZE_T) :: NMEM
  CALL DEALLOCATE_MEMORY_FFTW( FFTWMEM_PTR )
  IF (JPRB == JPRD) THEN
    FFTWMEM_PTR=FFTW_ALLOC_COMPLEX(NMEM)
  ELSE
    FFTWMEM_PTR=FFTWF_ALLOC_COMPLEX(NMEM)
  END IF
END SUBROUTINE ALLOCATE_MEMORY_FFTW

SUBROUTINE DEALLOCATE_MEMORY_FFTW( FFTWMEM_PTR )
  TYPE(C_PTR) :: FFTWMEM_PTR
  IF( C_ASSOCIATED(FFTWMEM_PTR) ) THEN
    IF (JPRB == JPRD) THEN
      CALL FFTW_FREE(FFTWMEM_PTR)
    ELSE
      CALL FFTWF_FREE(FFTWMEM_PTR)
    END IF
  END IF
END SUBROUTINE DEALLOCATE_MEMORY_FFTW

SUBROUTINE TPM_FFTW_EXECUTE_DFT_INV_R1(IPLAN_INV,ZFFT)
  IMPLICIT NONE
  INTEGER(KIND=JPIB) :: IPLAN_INV
  REAL(KIND=JPRB), CONTIGUOUS :: ZFFT(:)
  
  IF (JPRB == JPRD) THEN
     CALL DFFTW_EXECUTE_DFT_C2R(IPLAN_INV,ZFFT,ZFFT)
  ELSE
     CALL SFFTW_EXECUTE_DFT_C2R(IPLAN_INV,ZFFT,ZFFT)
  END IF
END SUBROUTINE TPM_FFTW_EXECUTE_DFT_INV_R1

SUBROUTINE TPM_FFTW_EXECUTE_DFT_INV_R2(IPLAN_INV,ZFFT)
  IMPLICIT NONE
  INTEGER(KIND=JPIB) :: IPLAN_INV
  REAL(KIND=JPRB), CONTIGUOUS :: ZFFT(:,:)
  
  IF (JPRB == JPRD) THEN
     CALL DFFTW_EXECUTE_DFT_C2R(IPLAN_INV,ZFFT,ZFFT)
  ELSE
     CALL SFFTW_EXECUTE_DFT_C2R(IPLAN_INV,ZFFT,ZFFT)
  END IF
END SUBROUTINE TPM_FFTW_EXECUTE_DFT_INV_R2

SUBROUTINE TPM_FFTW_EXECUTE_DFT_DIR_R1(IPLAN_DIR,ZFFT)
  IMPLICIT NONE
  INTEGER(KIND=JPIB) :: IPLAN_DIR
  REAL(KIND=JPRB), CONTIGUOUS :: ZFFT(:)
  
  IF (JPRB == JPRD) THEN
     CALL DFFTW_EXECUTE_DFT_R2C(IPLAN_DIR,ZFFT,ZFFT)
  ELSE
     CALL SFFTW_EXECUTE_DFT_R2C(IPLAN_DIR,ZFFT,ZFFT)
  END IF
END SUBROUTINE TPM_FFTW_EXECUTE_DFT_DIR_R1

SUBROUTINE TPM_FFTW_EXECUTE_DFT_DIR_R2(IPLAN_DIR,ZFFT)
  IMPLICIT NONE
  INTEGER(KIND=JPIB) :: IPLAN_DIR
  REAL(KIND=JPRB), CONTIGUOUS :: ZFFT(:,:)
  
  IF (JPRB == JPRD) THEN
     CALL DFFTW_EXECUTE_DFT_R2C(IPLAN_DIR,ZFFT,ZFFT)
  ELSE
     CALL SFFTW_EXECUTE_DFT_R2C(IPLAN_DIR,ZFFT,ZFFT)
  END IF
END SUBROUTINE TPM_FFTW_EXECUTE_DFT_DIR_R2

SUBROUTINE TPM_FFTW_FREE_MEMORY()
  IMPLICIT NONE

  IF (.NOT. LALLOPERM) THEN
     IF (JPRB == JPRD) THEN
        CALL FFTW_FREE(ZFFTWP)
     ELSE
        CALL FFTWF_FREE(ZFFTWP)
     END IF
     ZFFTWP_SIZE=0
     ZFFTWP = C_NULL_PTR
  END IF
END SUBROUTINE TPM_FFTW_FREE_MEMORY

SUBROUTINE TPM_FFTW_ALLOCATE_MEMORY_R1(KCLEN, ZFFT)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: ZFFT(:)
  
  INTEGER(KIND=C_SIZE_T) :: NMEM_PLAN_FFTW
  
  ! Only really allocate memory if needed
  NMEM_PLAN_FFTW=INT(KCLEN/2,C_SIZE_T)
  IF (ZFFTWP_SIZE < NMEM_PLAN_FFTW) THEN
    CALL ALLOCATE_MEMORY_FFTW(ZFFTWP, NMEM_PLAN_FFTW)
    ZFFTWP_SIZE = NMEM_PLAN_FFTW
  END IF
  ! ZFFTP is large enough to fit KCLEN*KFIELDS
  CALL C_F_POINTER(ZFFTWP,ZFFT,[KCLEN])
END SUBROUTINE TPM_FFTW_ALLOCATE_MEMORY_R1

SUBROUTINE TPM_FFTW_ALLOCATE_MEMORY_R2(KCLEN, KFIELDS, ZFFT)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KFIELDS
  REAL(KIND=JPRB), POINTER, CONTIGUOUS :: ZFFT(:,:)
  
  INTEGER(KIND=C_SIZE_T) :: NMEM_PLAN_FFTW
  
  ! Only really allocate memory if needed
  NMEM_PLAN_FFTW=INT(KCLEN/2*KFIELDS,C_SIZE_T)
  IF (ZFFTWP_SIZE < NMEM_PLAN_FFTW) THEN
    CALL ALLOCATE_MEMORY_FFTW(ZFFTWP, NMEM_PLAN_FFTW)
    ZFFTWP_SIZE = NMEM_PLAN_FFTW
  END IF
  ! ZFFTP is large enough to fit KCLEN*KFIELDS
  CALL C_F_POINTER(ZFFTWP,ZFFT,[KCLEN,KFIELDS])
END SUBROUTINE TPM_FFTW_ALLOCATE_MEMORY_R2

SUBROUTINE TPM_FFTW_DFT_INV_R1(KRLEN,KCLEN,KOFF,PREEL,PFFT,JF)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
  INTEGER(KIND=JPIM),INTENT(IN)   :: JF
  REAL(KIND=JPRB), CONTIGUOUS, INTENT(INOUT)  :: PREEL(:,:)
  REAL(KIND=JPRB) :: PFFT(KCLEN)

  INTEGER(KIND=JPIB) :: IPLAN_INV
  INTEGER(KIND=JPIM) :: JJ

  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  CALL TPM_FFTW_GET_PLAN_INV(IPLAN_INV,KRLEN)
  !DIR$ IVDEP
  DO JJ=1,KCLEN
     PFFT(JJ) =PREEL(JF,KOFF+JJ-1) ! FIXME this is a step, we need transpose of PREEL
  ENDDO

  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',0,ZHOOK_HANDLE)
  CALL TPM_FFTW_EXECUTE_DFT_INV(IPLAN_INV,PFFT)
  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',1,ZHOOK_HANDLE)

  DO JJ=1,KRLEN
     PREEL(JF,KOFF+JJ-1)=PFFT(JJ) ! FIXME this is a step, we need transpose of PREEL
  ENDDO
END SUBROUTINE TPM_FFTW_DFT_INV_R1

SUBROUTINE TPM_FFTW_DFT_INV_R1_INPLACE(KRLEN,KCLEN,KOFF,PREEL)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
  REAL(KIND=JPRB), CONTIGUOUS, INTENT(INOUT)  :: PREEL(:)

  INTEGER(KIND=JPIB) :: IPLAN_INV

  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  CALL TPM_FFTW_GET_PLAN_INV(IPLAN_INV,KRLEN)

  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',0,ZHOOK_HANDLE)
  CALL TPM_FFTW_EXECUTE_DFT_INV(IPLAN_INV,PREEL(KOFF:KOFF+KRLEN-1))
  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',1,ZHOOK_HANDLE)

END SUBROUTINE TPM_FFTW_DFT_INV_R1_INPLACE



SUBROUTINE TPM_FFTW_DFT_INV_R2(KRLEN,KCLEN,KOFF,KFIELDS,PREEL,PFFT)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
  INTEGER(KIND=JPIM),INTENT(IN)   :: KFIELDS
  REAL(KIND=JPRB), CONTIGUOUS, INTENT(INOUT)  :: PREEL(:,:)
  REAL(KIND=JPRB) :: PFFT(KCLEN)

  INTEGER(KIND=JPIB) :: IPLAN_INV
  INTEGER(KIND=JPIM) :: JF, JJ

  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  CALL TPM_FFTW_GET_PLAN_INV(IPLAN_INV,KRLEN)
  DO JF=1,KFIELDS
     !DIR$ IVDEP
     DO JJ=1,KCLEN
        PFFT(JJ) =PREEL(JF,KOFF+JJ-1)
     END DO

     IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',0,ZHOOK_HANDLE)
     CALL TPM_FFTW_EXECUTE_DFT_INV(IPLAN_INV,PFFT)
     IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_C2R',1,ZHOOK_HANDLE)

     DO JJ=1,KRLEN
        PREEL(JF,KOFF+JJ-1)=PFFT(JJ)
     END DO
  END DO
END SUBROUTINE TPM_FFTW_DFT_INV_R2

SUBROUTINE TPM_FFTW_DFT_DIR_R1(KRLEN,KCLEN,KOFF,PIN,PFFT)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
  REAL(KIND=JPRB), INTENT(INOUT), CONTIGUOUS :: PIN(:)
  REAL(KIND=JPRB), INTENT(INOUT) :: PFFT(KCLEN)

  INTEGER(KIND=JPIB) :: IPLAN_DIR
  INTEGER(KIND=JPIM) :: JJ

  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  CALL TPM_FFTW_GET_PLAN_DIR(IPLAN_DIR,KRLEN)
  DO JJ=1,KRLEN
     PFFT(JJ) =PIN(KOFF+JJ-1)
  ENDDO

  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',0,ZHOOK_HANDLE)
  CALL TPM_FFTW_EXECUTE_DFT_DIR(IPLAN_DIR,PFFT)
  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',1,ZHOOK_HANDLE)

  DO JJ=1,KCLEN
     PIN(KOFF+JJ-1)=PFFT(JJ)/REAL(KRLEN, JPRB)
  ENDDO
END SUBROUTINE TPM_FFTW_DFT_DIR_R1

SUBROUTINE TPM_FFTW_DFT_DIR_R1_INPLACE(KRLEN,KCLEN,KOFF,PIN)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
  REAL(KIND=JPRB), INTENT(INOUT), CONTIGUOUS :: PIN(:)

  INTEGER(KIND=JPIB) :: IPLAN_DIR
  INTEGER(KIND=JPIM) :: JJ

  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

  CALL TPM_FFTW_GET_PLAN_DIR(IPLAN_DIR,KRLEN)
  
  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',0,ZHOOK_HANDLE)
  CALL TPM_FFTW_EXECUTE_DFT_DIR(IPLAN_DIR,PIN(KOFF:KOFF+KCLEN-1))
  IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',1,ZHOOK_HANDLE)

  DO JJ=1,KCLEN
     PIN(KOFF+JJ-1)=PIN(KOFF+JJ-1)/REAL(KRLEN, JPRB)
  ENDDO
END SUBROUTINE TPM_FFTW_DFT_DIR_R1_INPLACE



SUBROUTINE TPM_FFTW_DFT_DIR_R2(KRLEN,KCLEN,KOFF,KFIELDS,PREEL,PFFT)
  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
  INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
  INTEGER(KIND=JPIM),INTENT(IN)   :: KFIELDS
  REAL(KIND=JPRB), CONTIGUOUS, INTENT(INOUT)  :: PREEL(:,:)
  REAL(KIND=JPRB) :: PFFT(KCLEN)

  INTEGER(KIND=JPIB) :: IPLAN_DIR
  INTEGER(KIND=JPIM) :: JF, JJ

  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
  CALL TPM_FFTW_GET_PLAN_DIR(IPLAN_DIR,KRLEN)
  DO JF=1,KFIELDS
     !DIR$ IVDEP
     DO JJ=1,KRLEN
        PFFT(JJ) =PREEL(KOFF+JJ-1,JF)
     ENDDO

     IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',0,ZHOOK_HANDLE)
     CALL TPM_FFTW_EXECUTE_DFT_DIR(IPLAN_DIR,PFFT)
     IF (LHOOK) CALL DR_HOOK('FFTW_EXECUTE_DFT_R2C',1,ZHOOK_HANDLE)
     DO JJ=1,KCLEN
        PREEL(KOFF+JJ-1,JF)=PFFT(JJ)/REAL(KRLEN, JPRB)
     ENDDO
  ENDDO
END SUBROUTINE TPM_FFTW_DFT_DIR_R2

SUBROUTINE EXEC_FFTW_MULTI_COLUMN(KTYPE,KRLEN,KCLEN,KOFF,KFIELDS,PREEL)
IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)   :: KTYPE
INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
INTEGER(KIND=JPIM),INTENT(IN)   :: KFIELDS
REAL(KIND=JPRB), CONTIGUOUS, INTENT(INOUT)  :: PREEL(:,:)

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: ZFFT1(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',0,ZHOOK_HANDLE)

IF ( (KTYPE /= -1) .AND. (KTYPE /=1) ) THEN
  CALL ABOR1('TPM_FFTW:EXEC_FFTW : WRONG VALUE KTYPE')
ENDIF

CALL TPM_FFTW_ALLOCATE_MEMORY(KCLEN, ZFFT1)

IF (KTYPE==1) THEN
   CALL TPM_FFTW_DFT_INV(KRLEN,KCLEN,KOFF,KFIELDS,PREEL,ZFFT1)
ELSE
   CALL TPM_FFTW_DFT_DIR(KRLEN,KCLEN,KOFF,KFIELDS,PREEL,ZFFT1)
END IF

CALL TPM_FFTW_FREE_MEMORY()

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',1,ZHOOK_HANDLE)
END SUBROUTINE EXEC_FFTW_MULTI_COLUMN

SUBROUTINE EXEC_FFTW_MULTI_COLUMN_INPLACE(KTYPE,KRLEN,KCLEN,KOFF,KFIELDS,PREEL)
IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)   :: KTYPE
INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
INTEGER(KIND=JPIM),INTENT(IN)   :: KFIELDS
REAL(KIND=JPRB), CONTIGUOUS, INTENT(INOUT)  :: PREEL(:,:)

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: ZFFT1(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',0,ZHOOK_HANDLE)

IF ( (KTYPE /= -1) .AND. (KTYPE /=1) ) THEN
  CALL ABOR1('TPM_FFTW:EXEC_FFTW : WRONG VALUE KTYPE')
ENDIF

CALL TPM_FFTW_ALLOCATE_MEMORY(KCLEN, ZFFT1)

IF (KTYPE==1) THEN
   CALL TPM_FFTW_DFT_INV(KRLEN,KCLEN,KOFF,KFIELDS,PREEL,ZFFT1)
ELSE
   CALL TPM_FFTW_DFT_DIR(KRLEN,KCLEN,KOFF,KFIELDS,PREEL,ZFFT1)
END IF

CALL TPM_FFTW_FREE_MEMORY()

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',1,ZHOOK_HANDLE)
END SUBROUTINE EXEC_FFTW_MULTI_COLUMN_INPLACE

SUBROUTINE EXEC_FFTW_SINGLE_COLUMN(KTYPE,KRLEN,KCLEN,KOFF,PIN,JF)
IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)   :: KTYPE
INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
REAL(KIND=JPRB), INTENT(INOUT), CONTIGUOUS :: PIN(:,:)
INTEGER(KIND=JPIM),INTENT(IN)   :: JF

REAL(KIND=JPRB), POINTER, CONTIGUOUS :: ZFFT1(:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',0,ZHOOK_HANDLE)

IF ( (KTYPE /= -1) .AND. (KTYPE /=1) ) THEN
  CALL ABOR1('TPM_FFTW:EXEC_FFTW : WRONG VALUE KTYPE')
ENDIF

CALL TPM_FFTW_ALLOCATE_MEMORY(KCLEN, ZFFT1)

IF (KTYPE==1) THEN
   CALL ABOR1('TPM_FFTW:EXEC_FFTW_INOUT : Inverse transform not implemented yet for single column')
   ! CALL TPM_FFTW_DFT_INV(KRLEN,KCLEN,KOFF,PIN(:,JF),ZFFT1)
ELSE
   CALL TPM_FFTW_DFT_DIR(KRLEN,KCLEN,KOFF,PIN(:,JF),ZFFT1)
END IF

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',1,ZHOOK_HANDLE)
END SUBROUTINE EXEC_FFTW_SINGLE_COLUMN

SUBROUTINE EXEC_FFTW_SINGLE_COLUMN_INPLACE(KTYPE,KRLEN,KCLEN,KOFF,PIN)
IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)   :: KTYPE
INTEGER(KIND=JPIM),INTENT(IN)   :: KRLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KCLEN
INTEGER(KIND=JPIM),INTENT(IN)   :: KOFF
REAL(KIND=JPRB), INTENT(INOUT), CONTIGUOUS :: PIN(:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',0,ZHOOK_HANDLE)

IF ( (KTYPE /= -1) .AND. (KTYPE /=1) ) THEN
  CALL ABOR1('TPM_FFTW:EXEC_FFTW : WRONG VALUE KTYPE')
ENDIF

IF (KTYPE==1) THEN
   CALL TPM_FFTW_DFT_INV(KRLEN,KCLEN,KOFF,PIN) ! Call inplace routine
ELSE
   CALL TPM_FFTW_DFT_DIR(KRLEN,KCLEN,KOFF,PIN) ! Call inplace routine
END IF

IF (LHOOK) CALL DR_HOOK('EXEC_FFTW',1,ZHOOK_HANDLE)
ENDSUBROUTINE EXEC_FFTW_SINGLE_COLUMN_INPLACE

END MODULE TPM_FFTW
